theme = "dark_plus"

[editor]
cursorline = true
rulers = [80, 120]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
character = "┆"

