# Language specific configurations for the editor
[[language]]
name = "python"
language-servers = [{ name = "pylsp", except-features = [ "format" ] }, "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]
